environment:
    nodejs_version: 10
    GITHUB_TOKEN:
        secure: 6ld2MBbd9Dep8sD6q3on5JHh2QBG2dSOPwS4Gp4/mG7/RLXdrB9H/ibNXI+4FeX+
branches:
  only:
    - master
    - develop
before_build:
install:
    # Get the latest stable version of Node.js or io.js
    - ps: Install-Product node $env:nodejs_version
    - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version 
    - ps: Update-AppveyorBuild -Version "$env:package_version-build-$env:APPVEYOR_BUILD_NUMBER"
    - npm -g install npm@6
    - npm -g install node-gyp
    - node --version
    - npm --version
    # install modules
    - npm ci
build: off
platform:
    - x64
before_package: echo Before package
test_script:
    - npm run buildcss
    - npm run publish
skip_non_tags: true
artifacts:
    - path: out/make/*.exe
      name: BeetSetup